version: '3.9'

services:


  api-gateway:
    image: payk96/rpg-shop-api-gateway:0.0.3
    container_name: api-gateway
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    restart: unless-stopped
    networks:
      - my_network

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped


  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    environment:
      - KC_DB=postgres
      - KC_DB_URL_HOST=keycloakSQL
      - KC_DB_URL_DATABASE=keycloak
      - KC_DB_USERNAME=postgres
      - KC_DB_PASSWORD=postgres
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - "8484:8080"
    command: start-dev
    depends_on:
      - keycloakSQL
    restart: unless-stopped
    networks:
      - my_network

  keycloakSQL:
    container_name: keycloakSQL
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=keycloak
    ports:
      - "5433:5432"
    volumes:
      - "/home/daniil/Desktop/keycloak_data:/var/lib/postgresql/data"
    restart: unless-stopped
    networks:
      - my_network

  rpg_shop_db:
    container_name: rpg_shop_db
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=rpg_shop_db
    ports:
      - "5432:5432"
    volumes:
      - "/home/daniil/Desktop/postgres_data:/var/lib/postgresql/data"
    restart: unless-stopped
    networks:
      - my_network

  items-service:
    image: payk96/rpg-shop-items-service:0.0.5
    container_name: items-service
    ports:
      - "8083:8080"
    environment:  
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - rpg_shop_db
    restart: unless-stopped
    networks:
      - my_network

  auth-service:
    image: payk96/rpg-shop-auth-service:0.0.2
    container_name: auth-service
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - KEYCLOAK_CLIENT_SECRET=3i9MjnwSECMQowksDN2zSxnhSAjJ4MQI
      - KEYCLOAK_PUBLIC_KEY=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEApE8E3hGkCLgX+Z3TukQyH6mE11oCl/nGAbQOVhG8K4fmB6JFT8W2StV6GhHYnezOOQgaRVzTkleneIINPR4Q2d2MC9idGNP6SsumXH7rHsETpZZ+cpV9Zl3E1q5lNEXf5zn/hEs+S0bzNg9zeYhDyESxnJdY9BSX8c0CWKbdq9DutSdDoiIRW95NLTiAvx6yZFbpACQQMot1/XPpAjtJajasG9PEiII7ZP7BzGQxR6zsQugDwiIntVQXhYTBQJJUP6sefEzABaYdMM1vEoDQ+agr4+BpcNTobAHmK300aNRgD8hTWOxlv2VXJXm0psum7IhupGyGIwD7XKWf0OD9JQIDAQAB
    depends_on:
      - keycloak
    restart: unless-stopped
    networks:
      - my_network

  notification-service:
    image: payk96/rpg-shop-notification-service:0.0.2
    container_name: notification-service
    ports:
      - "8082:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - kafka
    restart: unless-stopped
    networks:
      - my_network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - my_network
    healthcheck:
      test: [ "CMD-SHELL", "nc -z localhost 2181 || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 3


  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_INTERNAL://0.0.0.0:29092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    networks:
      - my_network
    healthcheck:
      test: ["CMD-SHELL", "kafka-topics --bootstrap-server kafka:29092 --list || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10



volumes:
  postgres_data:
  keycloak_data:

networks:
  my_network:
    driver: bridge