spring:
    application:
        name: rpg-shop
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: none
    datasource:
        rpgshop:
            driver-class-name: org.postgresql.Driver
            username: postgres
            password: postgres
    kafka:
        producer:
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
            properties:
                spring.json.add.type.headers: false

kafka:
    topic:
        order-created: order.created.events