spring:
  config:
    activate:
      on-profile: dev
  datasource:
    rpgshop:
      url: jdbc:postgresql://localhost:5432/rpg_shop_db
  kafka:
    bootstrap-servers: localhost:9092
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379


  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8484/realms/rpg-shop
