spring:
    application:
        name: rpg-shop
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: none
    datasource:
        rpgshop:
            driver-class-name: org.postgresql.Driver
            username: postgres
            password: postgres
    kafka:
        bootstrap-servers: localhost:9092
        producer:
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
            properties:
                spring.json.add.type.headers: false
        consumer:
            group-id: rpg-shop-group
            auto-offset-reset: earliest
            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
            properties:
                spring.json.trusted.packages: "com.payk96.rpg_shop.event"

kafka:
    topic:
        order-created: order.created.events