spring:
  config:
    activate:
      on-profile: prod
  datasource:
    rpgshop:
      url: jdbc:postgresql://rpg_shop_db:5432/rpg_shop_db
  kafka:
    bootstrap-servers: kafka:29092
  cache:
    type: redis
  redis:
    host: redis
    port: 6379

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/rpg-shop