spring:
    application:
        name: rpg-shop
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: none
    datasource:
        rpgshop:
            driver-class-name: org.postgresql.Driver
            username: postgres
            password: postgres
    kafka:
        producer:
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
            properties:
                spring.json.add.type.headers: false
    cache:
        type: redis
    redis:
        host: localhost
        port: 6379

kafka:
    topic:
        order-created: order.created.events

server:
    port: 8080


management:
    endpoints:
        web:
            exposure:
                include: "*"
    metrics:
        tags:
            application: rpg-shop


logging:
    level:
        org.springframework.security: DEBUG
        org.springframework.security.oauth2: DEBUG
        org.springframework.security.web.authentication: DEBUG
        org.springframework.security.web.access: DEBUG
